name 'phpInstall'
maintainer 'Keziah Zhou'
maintainer_email 'kezizhou@gmail.com'
license 'All Rights Reserved'
description 'Cookbook to install PHP7 and start Apache web server'
long_description 'Cookbook to install PHP7 and start Apache web server'
chef_version '>= 13.0'
issues_url 'https://github.com/kezizhou/phpInstall'
source_url 'https://github.com/kezizhou/phpInstall'
